version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: full_name
      - name: email
      - name: active

  - name: dim_film
    columns:
      - name: film_id
        tests:
          - unique
          - not_null
      - name: title
      - name: description
      - name: release_year
      - name: rental_duration
      - name: rental_rate
      - name: length
      - name: replacement_cost
      - name: rating
      - name: special_features
      - name: full_text

  - name: dim_staff
    columns:
      - name: staff_id
        tests:
          - unique
          - not_null
      - name: full_name
      - name: email
      - name: username
      - name: password
      - name: picture
      - name: active

  - name: dim_category
    columns:
      - name: category_id
        description: Primary key for categories.
        tests:
          - unique
          - not_null
      - name: name

  - name: dim_language
    columns:
      - name: language_id
        tests:
          - unique
          - not_null
      - name: name

  - name: dim_city
    columns:
      - name: city_id
        tests:
          - unique
          - not_null
      - name: city

  - name: dim_country
    columns:
      - name: country_id
        tests:
          - unique
          - not_null
      - name: country

  - name: fact_rental
    columns:
      - name: rental_id
        description: Primary key for rentals.
        tests:
          - unique
          - not_null
      - name: staff_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_staff')
              field: staff_id
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: category_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_category')
              field: category_id
      - name: film_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_film')
              field: film_id
      - name: language_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_language')
              field: language_id
      - name: city_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_city')
              field: city_id
      - name: country_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_country')
              field: country_id
      - name: rental_days
      - name: total_payment_amounts
